spring:
  application:
    name: poc-tracabilite
  datasource:
    url: jdbc:postgresql://localhost:5432/tracabilite
    username: postgres
    password: postgres
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/sipf-poc/protocol/openid-connect/certs

server:
  port: 9090

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    pf.gov.si.poc: DEBUG
    org.hibernate: ERROR